### PR TITLE
Add the new license key and add it to the env variables

### PR DESCRIPTION
**Pull request by vickipetrova**
# Pull Request Template

## Description

Added the permanent license key we got. Also add it as an env variable. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## What Has Changed

Please describe in bullets what you have changed.

- Env file
- Change 2
- Change 3

## How Has This Been Tested / How Can This Be Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- This doesn't work right now. The `process.env.SYNCFUSION_LICENSE_KEY` in the events view file shows up as null.

### CODE REVIEW

**Comment by vickipetrova** [comment]
@bathientran Can I ask you for help on this please? I'm doing something wrong in the way I'm registering the key in the env file and then when accessing it from the client side file it shows up as null -- basically I can't access the env variables there.

**Comment by bathientran** [comment]
@vickipetrova updated it! You just needed the NEXT_PUBLIC prefix since you are using the env variable client-facing :)

**Comment by vickipetrova** [comment]
@bathientran oh wow, I didn't know that haha, thank you!!

**Comment by minerva-startup-spring2024** [comment]
@vickipetrova let's merge this one? :)

**Comment by vickipetrova** [comment]
@minerva-startup-spring2024 yes, just need a quick review approval to merge @bathientran

**Review by bathientran — APPROVED** [review]

**Pull request merged**
